void Gaussian2D()
{
	// generate xy gaussian
	TF2 *gaus = new TF2("gaus","xygaus",-7,4,-4.5,5.5);
	gaus->SetParameters(4,-1.5,4,0.5,2);
	
	// create 2D histogram
	TH2F *h2 = new TH2F("h2","",40,-4,4,40,-20,20);

	// fill 2D hist with random variables generated by xy gaus
	for(int i=0;i<500;i++)
	{
		double randGen = gaus->GetRandom();
		h2->Fill(randGen);
	}

	// create 1D hist as x- and y-projections
	TH1D *projh2X = h2->ProjectionX();
	TH1D *projh2Y = h2->ProjectionY();
	
	// Drawing
	TCanvas *c1 = new TCanvas("c1","c1",900,900);
	gStyle->SetOptStat(0);

	TPad *center_pad = new TPad("center_pad","center_pad",0.0,0.0,0.6,0.6);
	center_pad->Draw();

	TPad *right_pad = new TPad("right_pad","right_pad",0.55,0.0,1.0,0.6);
	center_pad->Draw();

	TPad *top_pad = new TPad("rop_pad","rop_pad",0.0,0.55,0.6,1.0);
	center_pad->Draw();	

	center_pad->cd();
	gStyle->SetPalette(1);
	h2->Draw("COL");

	top_pad->cd();
	projh2X->SetFillColor(kBlue+1);
	h2->Draw("bar");

	right_pad->cd();
	projh2Y->SetFillColor(kBlue-2);
	h2->Draw("hbar");
	
	c1->cd();
	
}
